# fGUI code
FGUI_SRC     += fgui/fgui.c fgui/fgui_clearregion.c fgui/fgui_helper.c fgui/fgui_line.c fgui/fgui_sprite.c fgui/fgui_text.c fgui/fgui_extra.c
# Display driver
FGUI_SRC     += fgui/hw/ks0108.c
