/*
    FemtoGUI

    asciitable.h

    Copyright (c) 2007 Bastiaan van Kesteren <bas@edeation.nl>
    This program comes with ABSOLUTELY NO WARRANTY; for details see the file LICENSE.
    This program is free software; you can redistribute it and/or modify it under the terms
    of the GNU General Public License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.
*/
#define ASCII_READABLE_START    32
#define ASCII_READABLE_END      127
#define ASCII_READABLE_CHARS    95
#define ASCII_LENGTH            128

unsigned char asciitext[128][43] = {
    "SOH     (Start of Header)                  ",
    "STX     (Start of Text)                    ",
    "ETX     (End of Text)                      ",
    "EOT     (End of Transmission)              ",
    "ENQ     (Enquiry)                          ",
    "ACK     (Acknowledgment)                   ",
    "BEL     (Bell)                             ",
    "BS      (Backspace)                        ",
    "HT      (Horizontal Tab)                   ",
    "LF      (Line Feed)                        ",
    "VT      (Vertical Tab)                     ",
    "FF      (Form Feed)                        ",
    "CR      (Carriage Return)                  ",
    "SO      (Shift Out)                        ",
    "SI      (Shift In)                         ",
    "DLE     (Data Link Escape)                 ",
    "DC1     (XON) (Device Control 1)           ",
    "DC2     (Device Control 2)                 ",
    "DC3     (XOFF)(Device Control 3)           ",
    "DC4     (Device Control 4)                 ",
    "NAK     (Negative Acknowledgement)         ",
    "SYN     (Synchronous Idle)                 ",
    "ETB     (End of Trans. Block)              ",
    "CAN     (Cancel)                           ",
    "EM      (End of Medium)                    ",
    "SUB     (Substitute)                       ",
    "ESC     (Escape)                           ",
    "FS      (File Separator)                   ",
    "GS      (Group Separator)                  ",
    "RS      (Request to Send)(Record Separator)",
    "US      (Unit Separator)                   ",
    "SP      (Space)                            ",
    "!       (exclamation mark)                 ",  /* ASCII_READABLE_START */
    "\"      (double quote)                     ",
    "#       (number sign)                      ",
    "$       (dollar sign)                      ",
    "%       (percent)                          ",
    "&       (ampersand)                        ",
    "'       (single quote)                     ",
    "(       (left/opening parenthesis)         ",
    ")       (right/closing parenthesis)        ",
    "*       (asterisk)                         ",
    "+       (plus)                             ",
    ",       (comma)                            ",
    "-       (minus or dash)                    ",
    ".       (dot)                              ",
    "/       (forward slash)                    ",
    "0                                          ",
    "1                                          ",
    "2                                          ",
    "3                                          ",
    "4                                          ",
    "5                                          ",
    "6                                          ",
    "7                                          ",
    "8                                          ",
    "9                                          ",
    ":       (colon)                            ",
    ";       (semi-colon)                       ",
    "<       (less than)                        ",
    "=       (equal sign)                       ",
    ">       (greater than)                     ",
    "?       (question mark)                    ",
    "@       (AT symbol)                        ",
    "A                                          ",
    "B                                          ",
    "C                                          ",
    "D                                          ",
    "E                                          ",
    "F                                          ",
    "G                                          ",
    "H                                          ",
    "I                                          ",
    "J                                          ",
    "K                                          ",
    "L                                          ",
    "M                                          ",
    "N                                          ",
    "O                                          ",
    "P                                          ",
    "Q                                          ",
    "R                                          ",
    "S                                          ",
    "T                                          ",
    "U                                          ",
    "V                                          ",
    "W                                          ",
    "X                                          ",
    "Y                                          ",
    "Z                                          ",
    "[       (left/opening bracket)             ",
    "\\       (back slash)                       ",
    "]       (right/closing bracket)            ",
    "^       (caret/circumflex)                 ",
    "_       (underscore)                       ",
    "`                                          ",
    "a                                          ",
    "b                                          ",
    "c                                          ",
    "d                                          ",
    "e                                          ",
    "f                                          ",
    "g                                          ",
    "h                                          ",
    "i                                          ",
    "j                                          ",
    "k                                          ",
    "l                                          ",
    "m                                          ",
    "n                                          ",
    "o                                          ",
    "p                                          ",
    "q                                          ",
    "r                                          ",
    "s                                          ",
    "t                                          ",
    "u                                          ",
    "v                                          ",
    "w                                          ",
    "x                                          ",
    "y                                          ",
    "z                                          ",
    "{       (left/opening brace)               ",
    "|       (vertical bar)                     ",
    "}       (right/closing brace)              ",
    "~       (tilde)                            ",  /* ASCII_READABLE_END */
    "DEL     (delete)                           "
};
